name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Test
        run: npm run test

      - name: Deploy
        run: git config --global user.name 'okomesan'
        run: git config --global user.email '103940417+okomesanID@users.noreply.github.com'
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
        run: npm run deploy
